import type { Appointment } from "@/types";

// Dates relative to today so the calendar always shows appointments
function relativeDate(offsetDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split("T")[0];
}

const TODAY      = relativeDate(0);
const YESTERDAY  = relativeDate(-1);
const TOMORROW   = relativeDate(1);
const IN_2_DAYS  = relativeDate(2);
const IN_4_DAYS  = relativeDate(4);
const IN_7_DAYS  = relativeDate(7);

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    clientId: "c1",
    clientName: "Marina Foster",
    service: "Hair Hydration Treatment",
    professional: "Anna Reed",
    date: TODAY,
    time: "09:00",
    durationMinutes: 60,
    status: "confirmed",
    value: 180,
  },
  {
    id: "a2",
    clientId: "c2",
    clientName: "Rafael Stone",
    service: "Haircut + Beard Trim",
    professional: "Lucas Grant",
    date: TODAY,
    time: "10:30",
    durationMinutes: 45,
    status: "confirmed",
    value: 95,
  },
  {
    id: "a3",
    clientId: "c3",
    clientName: "Isabella Ferris",
    service: "Deep Facial Cleansing",
    professional: "Anna Reed",
    date: TODAY,
    time: "11:30",
    durationMinutes: 90,
    status: "pending",
    value: 220,
  },
  {
    id: "a4",
    clientId: "c4",
    clientName: "Bruno Walsh",
    service: "Relaxing Massage",
    professional: "Carla Nash",
    date: TODAY,
    time: "14:00",
    durationMinutes: 60,
    status: "confirmed",
    value: 160,
  },
  {
    id: "a5",
    clientId: "c5",
    clientName: "Fiona Lane",
    service: "Eyebrow Design",
    professional: "Anna Reed",
    date: TODAY,
    time: "15:30",
    durationMinutes: 30,
    status: "cancelled",
    value: 70,
  },
  {
    id: "a6",
    clientId: "c1",
    clientName: "Marina Foster",
    service: "Hair Coloring",
    professional: "Anna Reed",
    date: TOMORROW,
    time: "10:00",
    durationMinutes: 120,
    status: "confirmed",
    value: 320,
  },
  {
    id: "a7",
    clientId: "c6",
    clientName: "Thomas Ray",
    service: "Men's Haircut",
    professional: "Lucas Grant",
    date: TOMORROW,
    time: "11:00",
    durationMinutes: 30,
    status: "pending",
    value: 60,
  },
  {
    id: "a8",
    clientId: "c3",
    clientName: "Isabella Ferris",
    service: "Chemical Peel",
    professional: "Carla Nash",
    date: IN_2_DAYS,
    time: "09:30",
    durationMinutes: 60,
    status: "confirmed",
    value: 280,
  },
  {
    id: "a9",
    clientId: "c7",
    clientName: "Camille Norton",
    service: "Anti-aging Facial",
    professional: "Carla Nash",
    date: IN_2_DAYS,
    time: "14:00",
    durationMinutes: 75,
    status: "confirmed",
    value: 310,
  },
  {
    id: "a10",
    clientId: "c8",
    clientName: "Diego Marsh",
    service: "Men's Haircut",
    professional: "Lucas Grant",
    date: IN_4_DAYS,
    time: "10:00",
    durationMinutes: 30,
    status: "pending",
    value: 60,
  },
  {
    id: "a11",
    clientId: "c2",
    clientName: "Rafael Stone",
    service: "Beard Shaping",
    professional: "Lucas Grant",
    date: IN_7_DAYS,
    time: "09:00",
    durationMinutes: 30,
    status: "confirmed",
    value: 55,
  },
  {
    id: "a12",
    clientId: "c4",
    clientName: "Bruno Walsh",
    service: "Sports Massage",
    professional: "Carla Nash",
    date: YESTERDAY,
    time: "16:00",
    durationMinutes: 60,
    status: "confirmed",
    value: 160,
  },
];
